db:
  driver:   postgres
  host:     db
  port:     5432
  database: fern
  username: fern
  password: fern
  detail-log:     true
  max-open-conns: 100
  max-idle-conns: 10
server:
  port: :8080
auth:
  json-web-keys-endpoint: ""
  enabled: "false"
  scope-claim-name: "scope"
header: "Fern Acceptance Test Report"